### ISSUE TITLE
user

### ISSUE THREAD

**Issue by sec13b** [n3rada/zero-effort#6]
if have user test and password test.

**Comment by n3rada** [comment]
Could you please describe more closely your problem? I do not get it.

**Comment by n3rada** [comment]
Without a more precise explanation of the problem, I'm having trouble pinpointing it. What's wrong? Can you show me the logs?

**Comment by n3rada** [comment]
I think that everything is said no? Are you sure than your target is vulnerable?

**Comment by n3rada** [comment]
A pleasure!
